# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'armoir' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for armoir
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

target 'armoirTests' do
    inherit! :search_paths
    # Pods for testing
  end


end
